title: Albert Sunny's Homepage
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  My Personal Homepage
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  albert-sunny
permalink: :title

repository: "albert-sunny/albert-sunny.github.io"

# Build settings
#plugins:
#  - jekyll-feed

# A list of the pages to display in the navigation bar
header_pages:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh

show_excerpts: true
